// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvlOB1h4Ojtes2qto1BpYWVkKAgu0u7_w',
    appId: '1:212170983835:ios:5a729df7f0c3817a83393e',
    messagingSenderId: '212170983835',
    projectId: 'group7chatapp',
    storageBucket: 'group7chatapp.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvlOB1h4Ojtes2qto1BpYWVkKAgu0u7_w',
    appId: '1:212170983835:ios:5a729df7f0c3817a83393e',
    messagingSenderId: '212170983835',
    projectId: 'group7chatapp',
    storageBucket: 'group7chatapp.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMB7MiPYAecUbdyzhXnmqbs5ReTBRBNO4',
    appId: '1:212170983835:web:a373c230abf2278183393e',
    messagingSenderId: '212170983835',
    projectId: 'group7chatapp',
    authDomain: 'group7chatapp.firebaseapp.com',
    storageBucket: 'group7chatapp.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMB7MiPYAecUbdyzhXnmqbs5ReTBRBNO4',
    appId: '1:212170983835:web:a373c230abf2278183393e',
    messagingSenderId: '212170983835',
    projectId: 'group7chatapp',
    authDomain: 'group7chatapp.firebaseapp.com',
    storageBucket: 'group7chatapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg-Ktef4JDUAgmlYGKTKbP1IvFVmkzzfM',
    appId: '1:212170983835:android:5c250703f09d7a0583393e',
    messagingSenderId: '212170983835',
    projectId: 'group7chatapp',
    storageBucket: 'group7chatapp.firebasestorage.app',
  );

}